name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make check ENABLE_GCOV=1
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
